#include "../common.hpp"

int main()
{
	clock_t t;
	clock_t ft_time;
	clock_t std_time;

	{
		ft::vector<std::string>	vec00(100, "string");
		ft::vector<std::string>	vec01(100, "string");
		ft::vector<std::string>	vec02(100, "string");
		ft::vector<std::string>	vec03(100, "string");
		ft::vector<std::string>	vec04(100, "string");
		ft::vector<std::string>	vec05(100, "string");
		ft::vector<std::string>	vec06(100, "string");
		ft::vector<std::string>	vec07(100, "string");
		ft::vector<std::string>	vec08(100, "string");
		ft::vector<std::string>	vec09(100, "string");
		ft::vector<std::string>	vec10(100, "string");
		ft::vector<std::string>	vec11(100, "string");
		ft::vector<std::string>	vec12(100, "string");
		ft::vector<std::string>	vec13(100, "string");
		ft::vector<std::string>	vec14(100, "string");
		ft::vector<std::string>	vec15(100, "string");
		ft::vector<std::string>	vec16(100, "string");
		ft::vector<std::string>	vec17(100, "string");
		ft::vector<std::string>	vec18(100, "string");
		ft::vector<std::string>	vec19(100, "string");
		ft::vector<std::string>	vec20(100, "string");
		ft::vector<std::string>	vec21(100, "string");
		ft::vector<std::string>	vec22(100, "string");
		ft::vector<std::string>	vec23(100, "string");
		ft::vector<std::string>	vec24(100, "string");
		ft::vector<std::string>	vec25(100, "string");
		ft::vector<std::string>	vec26(100, "string");
		ft::vector<std::string>	vec27(100, "string");
		ft::vector<std::string>	vec28(100, "string");
		ft::vector<std::string>	vec29(100, "string");
		ft::vector<std::string>	vec30(100, "string");
		ft::vector<std::string>	vec31(100, "string");
		ft::vector<std::string>	vec32(100, "string");
		ft::vector<std::string>	vec33(100, "string");
		ft::vector<std::string>	vec34(100, "string");
		ft::vector<std::string>	vec35(100, "string");
		ft::vector<std::string>	vec36(100, "string");
		ft::vector<std::string>	vec37(100, "string");
		ft::vector<std::string>	vec38(100, "string");
		ft::vector<std::string>	vec39(100, "string");
		ft::vector<std::string>	vec40(100, "string");
		ft::vector<std::string>	vec41(100, "string");
		ft::vector<std::string>	vec42(100, "string");
		ft::vector<std::string>	vec43(100, "string");
		ft::vector<std::string>	vec44(100, "string");
		ft::vector<std::string>	vec45(100, "string");
		ft::vector<std::string>	vec46(100, "string");
		ft::vector<std::string>	vec47(100, "string");
		ft::vector<std::string>	vec48(100, "string");
		ft::vector<std::string>	vec49(100, "string");
		t = clock();
	}
	ft_time = clock() - t;
	{
		std::vector<std::string>	vec00(100, "string");
		std::vector<std::string>	vec01(100, "string");
		std::vector<std::string>	vec02(100, "string");
		std::vector<std::string>	vec03(100, "string");
		std::vector<std::string>	vec04(100, "string");
		std::vector<std::string>	vec05(100, "string");
		std::vector<std::string>	vec06(100, "string");
		std::vector<std::string>	vec07(100, "string");
		std::vector<std::string>	vec08(100, "string");
		std::vector<std::string>	vec09(100, "string");
		std::vector<std::string>	vec10(100, "string");
		std::vector<std::string>	vec11(100, "string");
		std::vector<std::string>	vec12(100, "string");
		std::vector<std::string>	vec13(100, "string");
		std::vector<std::string>	vec14(100, "string");
		std::vector<std::string>	vec15(100, "string");
		std::vector<std::string>	vec16(100, "string");
		std::vector<std::string>	vec17(100, "string");
		std::vector<std::string>	vec18(100, "string");
		std::vector<std::string>	vec19(100, "string");
		std::vector<std::string>	vec20(100, "string");
		std::vector<std::string>	vec21(100, "string");
		std::vector<std::string>	vec22(100, "string");
		std::vector<std::string>	vec23(100, "string");
		std::vector<std::string>	vec24(100, "string");
		std::vector<std::string>	vec25(100, "string");
		std::vector<std::string>	vec26(100, "string");
		std::vector<std::string>	vec27(100, "string");
		std::vector<std::string>	vec28(100, "string");
		std::vector<std::string>	vec29(100, "string");
		std::vector<std::string>	vec30(100, "string");
		std::vector<std::string>	vec31(100, "string");
		std::vector<std::string>	vec32(100, "string");
		std::vector<std::string>	vec33(100, "string");
		std::vector<std::string>	vec34(100, "string");
		std::vector<std::string>	vec35(100, "string");
		std::vector<std::string>	vec36(100, "string");
		std::vector<std::string>	vec37(100, "string");
		std::vector<std::string>	vec38(100, "string");
		std::vector<std::string>	vec39(100, "string");
		std::vector<std::string>	vec40(100, "string");
		std::vector<std::string>	vec41(100, "string");
		std::vector<std::string>	vec42(100, "string");
		std::vector<std::string>	vec43(100, "string");
		std::vector<std::string>	vec44(100, "string");
		std::vector<std::string>	vec45(100, "string");
		std::vector<std::string>	vec46(100, "string");
		std::vector<std::string>	vec47(100, "string");
		std::vector<std::string>	vec48(100, "string");
		std::vector<std::string>	vec49(100, "string");
		t = clock();
	}
	std_time = clock() - t;
	efficiency_output(ft_time, std_time);
	return 0;
}